spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
  # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
  datasource:
    druid:
      username: transaction
      password: 123456
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: user
        login-password: user
        allow:
        deny:
  application:
    name: transaction

server:
  port: 18080

# Log配置
logging:
  #file: /logs/${spring.application.name}/${spring.application.name}.log
  file: ./logs/${spring.application.name}/${spring.application.name}.log
zt:
  enabled: true
# 配置缓存时间，60秒
cacheTime: 60000